### PR TITLE
added MIT licence.

### PR DESCRIPTION
**Pull request by benedictvscriticus**
Hi! Could you please approve the licensing change we discussed?

### CODE REVIEW

**Comment by memosys** [comment]
should be .md file? @plor  or without any extension?

**Comment by benedictvscriticus** [comment]
@memosys afaik its a txt file that is required, but please confirm @plor .

**Comment by memosys** [comment]
what is `baaspoolsllc` @benedictvscriticus ?

**Comment by benedictvscriticus** [comment]
Thanks for spotting this @memosys. That's a copy paste mistake.

**Pull request merged**
