### PR TITLE
adding documentation and readme updates

### PR DESCRIPTION
**Pull request by benedictvscriticus**

### CODE REVIEW

**Review by memosys — CHANGES_REQUESTED** [review]
Not good enough to merge yet, please run the unstructured parts through ai first

**Comment by benedictvscriticus** [comment]
@memosys this session was to give you guidance on what to write and you said that you will run it through chat gpt so please take it over.

**Comment by plor** [comment]
@memosys let's just work on this branch directly

**Comment by benedictvscriticus** [comment]
@memosys @plor I'm happy to collaborate on documentation, but even if I was to run it through an AI only @memosys can say whether it is acurrate.

**Comment by plor** [comment]
I was having issues updating this branch to get it to a good state. My git skills were lacking it seems. Please switch to building off of https://github.com/porters-xyz/gateway-demo/pull/308 instead.

**Pull request closed without merging**
